### ISSUE TITLE
Plans for Logstash output google pubsub

### ISSUE THREAD

**Issue by cvdsouza** [logstash-plugins/logstash-output-google_pubsub#1]
Hi , 
Just curious , what the plans and timelines are for this plugin. 
Currently at dayjob we're using https://github.com/NirKamara/logstash-output-google-cloud-pubsub  plugin to successfully get logs into pubsub. But would like to get the community's thoughts on if this would be the ideal way or if there might be some pitfalls we need to be aware off. 

Thanks for the great plugins :) 

Clinton

**Comment by josephlewis42** [comment]
Hey Clinton,

I have a plugin that's going through final review/checks now before I make a PR here for the Elastic folks to ask for inclusion here. It was delayed a bit once we realized that the old Google Cloud Ruby library was starting to give people SSL errors so I had to move it to the Java library instead.

Looking at that library I'd have a couple of concerns:

1. It looks like it turns off SSL verification, leaving you vulnerable to MITM attacks.
2. The plugin doesn't have any tests.
3. As far as I can tell, the publish condition is only after N messages are received so if your job only sends out N-1 messages they'll be stuck in Logstash; this issue is compounded because of threading so there could be (N-1)*T messages stuck.
4. The plugin seems to throw away messages if it doesn't have the capacity to queue them in RAM rather than letting you handle it correctly using Logstash's [persistent queues](https://www.elastic.co/guide/en/logstash/current/persistent-queues.html)

If you star this repo or leave this issue open I can ping you once it's merged in (or maybe before as a beta-tester?)

Cheers!
- Joseph

**Comment by cvdsouza** [comment]
Hi Joseph, 
Thank you very much for pointing these out. I didn't realize concern# 1 and that's a big one.  
We've definitely had issues with messages being dropped cause the queue gets filled very quickly. I'm definitely open to being a beta-tester. So please let me know when you'd like me to test.

Thanks, 
Clinton

**Comment by josephlewis42** [comment]
Alright, things have been approved and I have an [pre-release gemfile and documentation](https://github.com/josephlewis42/logstash-output-google_pubsub/releases/tag/v1.0.0-pre) for testing. 

@cvdsouza if you do any testing, please leave your feedback. Elastic likes to see some community sign-off before merging.

**Comment by josephlewis42** [comment]
Hi @cvdsouza,

The plugin is now released with version 1.0. There's a known issue #7 if you're going to use it with the other Logstash Pub/Sub plugin, but we have a potential fix for that and are just waiting for the fix to be confirmed.

Cheers!
\- Joseph
